tasks:
  aws-cli:
    name: Install AWS CLI
    triggeredBy:
      - postEnvironmentStart
    command: |
      cd /tmp
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      sudo ./aws/install --update
      echo "export AWS_CLI_AUTO_PROMPT=on-partial" >> ~/.bashrc
      source ~/.bashrc
      aws --version
